apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-service
spec:
  selector:
    app: {{ .Values.application.name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}