name: CI Pipeline

on:
  push:
    branches: [ main ]
    # Skip CI runs that were triggered by the CI itself
    paths-ignore:
       - 'helm/**'
       - 'k8s/**'
       - 'README.md'
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Check if test script exists
        id: check_tests
        run: |
          if grep -q '"test":' package.json; then
            echo "has_tests=true" >> $GITHUB_OUTPUT
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Run tests
        if: steps.check_tests.outputs.has_tests == 'true'
        run: npm test
      
      - name: Skip tests
        if: steps.check_tests.outputs.has_tests == 'false'
        run: echo "No test script found in package.json, skipping tests"

  code-quality:
    name: Code Quality
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint code (warnings only)
        run: npm run lint -- --max-warnings=100 || echo "Linting has warnings but we'll continue"
        
      - name: Check if format script exists
        id: check_format
        run: |
          if grep -q '"format:check":' package.json; then
            echo "has_format=true" >> $GITHUB_OUTPUT
          else
            echo "has_format=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Check formatting
        if: steps.check_format.outputs.has_format == 'true'
        run: npm run format:check || echo "Formatting issues found but we'll continue"
      
      - name: Skip formatting check
        if: steps.check_format.outputs.has_format == 'false'
        run: echo "No format:check script found in package.json, skipping format check"

  build-and-push-docker:
    name: Build and Push Docker Image
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Extract last 4 digits of run ID
        id: extract_id
        run: echo "SHORT_ID=$(echo ${{ github.run_id }} | tail -c 5)" >> $GITHUB_OUTPUT
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-devopsified:${{ steps.extract_id.outputs.SHORT_ID }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-helm-chart:
    name: Update Helm Chart
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          
      - name: Extract last 4 digits of run ID
        id: extract_id
        run: echo "SHORT_ID=$(echo ${{ github.run_id }} | tail -c 5)" >> $GITHUB_OUTPUT
          
      - name: Update image tag in Helm values
        run: |
          sed -i "s/tag: .*/tag: ${{ steps.extract_id.outputs.SHORT_ID }}/" ./helm/portfolio-devopsified-chart/values.yaml
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'Bilal Ashraf'
          git config --global user.email 'beingbilalashraf@gmail.com'
          git add ./helm/portfolio-devopsified-chart/values.yaml
          git commit -m "Update Helm chart with new image tag: ${{ steps.extract_id.outputs.SHORT_ID }}"
          git push